services:
  redis:
    image: redis:7-alpine
    container_name: disasterwatch-redis

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    restart: always

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: disasterwatch-backend
    ports: 
    - "5000:5000"

    env_file:
      - .env

    depends_on:
      redis:
        condition: service_healthy

    restart: always

